#!/usr/bin/env bash

if [ "$(uname -s)" = "Darwin" ]; then
    nix-shell shell.nix --attr darwin
else
    if [ ! -d nixGL/ ]; then
        git clone https://github.com/albertgoncalves/nixGL.git
        (
            cd nixGL/ || exit 1
            driver_version=$(
                grep "X Driver" /var/log/Xorg.0.log \
                    | sed 's/^.*X Driver  \(\S*\)\s*.*/\1/'
            )
            ./nvidiaInstall.py "$driver_version" nixGLNvidia
        )
    fi
    nix-shell shell.nix --attr linux
fi
