#!/usr/bin/env bash

set -e

if [ ! "$(uname -s)" = "Linux" ] || [ -z "$1" ]; then
    exit 1
fi

sudo sh -c " echo 0 > /proc/sys/kernel/kptr_restrict"
perf record --call-graph lbr "$1"
perf report
rm perf.data*
valgrind --tool=cachegrind "$1"
rm cachegrind.out.*
