#!/usr/bin/env bash

set -e

if [ ! "$(uname -s)" = "Linux" ] || [ -z "$1" ]; then
    exit 1
fi

sudo sh -c "echo 1 > /proc/sys/kernel/perf_event_paranoid"
sudo sh -c "echo 0 > /proc/sys/kernel/kptr_restrict"
perf record --call-graph fp "$1"
perf report
rm perf.data*

if [ -z "$2" ]; then
    exit 0
fi

valgrind --tool=cachegrind --branch-sim=yes "$1"
rm cachegrind.out.*
